In [14]:
# 1.feladat: Számítsuk ki az A és B mátrixok rangját, inverzét és determinánsát!
import numpy as np

In [15]:
A=np.array([[1,2,3],[2,3,4],[3,4,6]])
A

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 6]])

In [16]:
B=np.array([[1,0,0,0],[2,1,0,0],[3,2,1,0],[4,3,2,1]])
B

array([[1, 0, 0, 0],
       [2, 1, 0, 0],
       [3, 2, 1, 0],
       [4, 3, 2, 1]])

In [17]:
# inverz:
Ai=np.linalg.inv(A)
Ai

array([[-2.00000000e+00,  5.92118946e-16,  1.00000000e+00],
       [-3.33066907e-16,  3.00000000e+00, -2.00000000e+00],
       [ 1.00000000e+00, -2.00000000e+00,  1.00000000e+00]])

In [18]:
Bi=np.linalg.inv(B)
Bi

array([[ 1.00000000e+00,  1.11022302e-16,  0.00000000e+00,
         0.00000000e+00],
       [-2.00000000e+00,  1.00000000e+00, -0.00000000e+00,
        -0.00000000e+00],
       [ 1.00000000e+00, -2.00000000e+00,  1.00000000e+00,
        -0.00000000e+00],
       [ 2.22044605e-16,  1.00000000e+00, -2.00000000e+00,
         1.00000000e+00]])

In [19]:
# rang:
R1 = np.linalg.matrix_rank(Ai)
R1

3

In [20]:
R2 = np.linalg.matrix_rank(Bi)
R2

4

In [21]:
# determináns:
D1=np.linalg.det(Ai)
D1

-1.000000000000001

In [22]:
D2=np.linalg.det(Bi)
D2

0.9999999999999996

In [23]:
# 2.feladat:  Oldja meg a következő egyenletrendszert a Gauss módszerrel és az inverz mátrix-szal is.
C=np.array([[4,1,2],[2,4,1],[1,2,4]])

In [24]:
D=np.array([8,4,9])

In [25]:
# Gauss módszer:
x=np.linalg.solve(C,D)
x

array([1., 0., 2.])

In [26]:
ellenorzes=np.allclose(np.dot(C,x),D)
ellenorzes

True

In [27]:
# Inverz mátrix módszer:
Ci=np.linalg.inv(C)
Ci

array([[ 0.28571429,  0.        , -0.14285714],
       [-0.14285714,  0.28571429,  0.        ],
       [ 0.        , -0.14285714,  0.28571429]])

In [28]:
x=np.dot(Ci,D)
x

array([1., 0., 2.])

In [29]:
ellenorzes2=np.allclose(np.dot(C,x),D)
ellenorzes2

True

In [30]:
# piac:
E=np.array([[2,2,1],[3,2,0.5],[2,1,1]])
E

array([[2. , 2. , 1. ],
       [3. , 2. , 0.5],
       [2. , 1. , 1. ]])

In [31]:
F=np.array([[180,100,130],[390,420,360],[210,210,230]])
F

array([[180, 100, 130],
       [390, 420, 360],
       [210, 210, 230]])

In [32]:
EF=np.dot(E,F)
EF

array([[1350., 1250., 1210.],
       [1425., 1245., 1225.],
       [ 960.,  830.,  850.]])

In [33]:
print(EF.min(axis=1))

[1210. 1225.  830.]


In [34]:
# 3.feladat: Anti, Bori, Cili almát, banánt és citromot vesz a piacon, a hipermarketben vagy a csarnokban. 
# Ha csak az ár számít, melyikük hol vásároljon?

In [35]:
aruk = {
    "alma": {"csarnok": 180, "hipermarket": 100, "piac": 130},
    "banán": {"csarnok": 390, "hipermarket": 420, "piac": 360},
    "citrom": {"csarnok": 210, "hipermarket": 210, "piac": 230}
}

In [36]:
mennyisegek = {
    "Anti": {"alma": 2, "banán": 2, "citrom": 1},
    "Bori": {"alma": 3, "banán": 2, "citrom": 0.5},
    "Cili": {"alma": 2, "banán": 2, "citrom": 1}
}

In [37]:
boltok = ["csarnok", "hipermarket", "piac"]

In [38]:
ossz_arak = {}
for nev, mennyisegek_dict in mennyisegek.items():
    ossz_arak[nev] = {}
    for bolt in boltok:
        ossz_ar = sum(mennyisegek_dict[gyumolcs] * aruk[gyumolcs][bolt] for gyumolcs in mennyisegek_dict)
        ossz_arak[nev][bolt] = ossz_ar

In [39]:
legolcsobb_bolt = {}
for nev, arak in ossz_arak.items():
    legolcsobb_bolt[nev] = min(arak, key=arak.get)

In [42]:
for nev, bolt in legolcsobb_bolt.items():
    print(f"{nev} legolcsóbban {bolt}on vásárolhat.")

Anti legolcsóbban piacon vásárolhat.
Bori legolcsóbban piacon vásárolhat.
Cili legolcsóbban piacon vásárolhat.
